export const SUCCESS_ADD_USER = "SUCCESS_ADD_USER";
export const ERROR_ADD_USER = "ERROR_ADD_USER";

export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN";
export const ERROR_USER_LOGIN = "ERROR_USER_LOGIN";

export const SUCCESS_USER_DETAILS = "SUCCESS_USER_DETAILS";
export const ERROR_USER_DETAILS = "ERROR_USER_DETAILS";
